project:
  type: website

website:
  title: "Bingrui Qiao"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: journal
    toc: true

